/* 지역 검색 인덱스 (자동생성) */
window.REGION_INDEX=[
{s:"gangnam",n:"서울 강남구",g:"서울",a:"강남구 서울 서울특별시 서울시 역삼동 개포동 청담동 삼성동 대치동 신사동 논현동 압구정동 세곡동 자곡동 율현동 일원동 수서동 도곡동"},
{s:"gangdong",n:"서울 강동구",g:"서울",a:"강동구 서울 서울특별시 서울시 강일동 상일동 명일동 고덕동 암사동 천호동 성내동 길동 둔촌동"},
{s:"gangbuk",n:"서울 강북구",g:"서울",a:"강북구 서울 서울특별시 서울시 미아동 번동 수유동 우이동"},
{s:"gangseo",n:"서울 강서구",g:"서울",a:"강서구 서울 서울특별시 서울시 염창동 등촌동 화곡동 가양동 마곡동 내발산동 외발산동 공항동 방화동 개화동"},
{s:"gwanak",n:"서울 관악구",g:"서울",a:"관악구 서울 서울특별시 서울시 봉천동 신림동 남현동"},
{s:"gwangjin",n:"서울 광진구",g:"서울",a:"광진구 서울 서울특별시 서울시 중곡동 능동 구의동 광장동 자양동 화양동 군자동"},
{s:"guro",n:"서울 구로구",g:"서울",a:"구로구 서울 서울특별시 서울시 신도림동 구로동 가리봉동 고척동 개봉동 오류동 궁동 온수동 천왕동 항동"},
{s:"geumcheon",n:"서울 금천구",g:"서울",a:"금천구 서울 서울특별시 서울시 가산동 독산동 시흥동"},
{s:"nowon",n:"서울 노원구",g:"서울",a:"노원구 서울 서울특별시 서울시 월계동 공릉동 하계동 상계동 중계동"},
{s:"dobong",n:"서울 도봉구",g:"서울",a:"도봉구 서울 서울특별시 서울시 쌍문동 방학동 창동 도봉동"},
{s:"dongdaemun",n:"서울 동대문구",g:"서울",a:"동대문구 서울 서울특별시 서울시 신설동 용두동 제기동 전농동 답십리동 장안동 청량리동 회기동 휘경동 이문동"},
{s:"dongjak",n:"서울 동작구",g:"서울",a:"동작구 서울 서울특별시 서울시 노량진동 상도동 본동 흑석동 사당동 대방동 신대방동"},
{s:"mapo",n:"서울 마포구",g:"서울",a:"마포구 서울 서울특별시 서울시 아현동 공덕동 도화동 용강동 대흥동 염리동 신수동 서교동 동교동 합정동 망원동 연남동 성산동 상암동"},
{s:"seodaemun",n:"서울 서대문구",g:"서울",a:"서대문구 서울 서울특별시 서울시 홍제동 홍은동 남가좌동 북가좌동 연희동 신촌동 대현동 북아현동 충정로 천연동 현저동"},
{s:"seocho",n:"서울 서초구",g:"서울",a:"서초구 서울 서울특별시 서울시 서초동 잠원동 반포동 방배동 양재동 우면동 내곡동 염곡동 신원동"},
{s:"seongdong",n:"서울 성동구",g:"서울",a:"성동구 서울 서울특별시 서울시 왕십리동 마장동 사근동 행당동 응봉동 금호동 옥수동 성수동 송정동 용답동 도선동"},
{s:"seongbuk",n:"서울 성북구",g:"서울",a:"성북구 서울 서울특별시 서울시 성북동 돈암동 삼선동 동선동 안암동 보문동 정릉동 길음동 종암동 하월곡동 상월곡동 장위동 석관동"},
{s:"songpa",n:"서울 송파구",g:"서울",a:"송파구 서울 서울특별시 서울시 잠실동 신천동 풍납동 송파동 석촌동 삼전동 가락동 문정동 장지동 방이동 오금동 거여동 마천동"},
{s:"yangcheon",n:"서울 양천구",g:"서울",a:"양천구 서울 서울특별시 서울시 신정동 목동 신월동"},
{s:"yeongdeungpo",n:"서울 영등포구",g:"서울",a:"영등포구 서울 서울특별시 서울시 영등포동 여의도동 당산동 도림동 문래동 양평동 신길동 대림동"},
{s:"yongsan",n:"서울 용산구",g:"서울",a:"용산구 서울 서울특별시 서울시 후암동 남영동 청파동 원효로 이태원동 한남동 서빙고동 보광동 이촌동 효창동 용문동 한강로"},
{s:"eunpyeong",n:"서울 은평구",g:"서울",a:"은평구 서울 서울특별시 서울시 수색동 녹번동 불광동 갈현동 구산동 대조동 응암동 역촌동 신사동 증산동 진관동"},
{s:"jongno",n:"서울 종로구",g:"서울",a:"종로구 서울 서울특별시 서울시 청운동 효자동 사직동 세종로 청진동 삼청동 가회동 계동 안국동 혜화동 명륜동 창신동 숭인동 부암동 평창동 구기동 무악동 교남동 이화동 인사동"},
{s:"junggu",n:"서울 중구",g:"서울",a:"중구 서울 서울특별시 서울시 무교동 을지로 소공동 회현동 충무로 명동 필동 장충동 광희동 신당동 황학동 중림동 만리동 서소문동 정동 순화동 예장동"},
{s:"jungnang",n:"서울 중랑구",g:"서울",a:"중랑구 서울 서울특별시 서울시 면목동 상봉동 중화동 묵동 망우동 신내동"},
{s:"busan-junggu",n:"부산 중구",g:"부산",a:"중구 부산 부산광역시 "},
{s:"busan-seogu",n:"부산 서구",g:"부산",a:"서구 부산 부산광역시 "},
{s:"busan-donggu",n:"부산 동구",g:"부산",a:"동구 부산 부산광역시 "},
{s:"busan-yeongdo",n:"부산 영도구",g:"부산",a:"영도구 부산 부산광역시 "},
{s:"busan-jin",n:"부산 부산진구",g:"부산",a:"부산진구 부산 부산광역시 "},
{s:"busan-dongnae",n:"부산 동래구",g:"부산",a:"동래구 부산 부산광역시 "},
{s:"busan-namgu",n:"부산 남구",g:"부산",a:"남구 부산 부산광역시 "},
{s:"busan-bukgu",n:"부산 북구",g:"부산",a:"북구 부산 부산광역시 "},
{s:"busan-haeundae",n:"부산 해운대구",g:"부산",a:"해운대구 부산 부산광역시 "},
{s:"busan-saha",n:"부산 사하구",g:"부산",a:"사하구 부산 부산광역시 "},
{s:"busan-geumjeong",n:"부산 금정구",g:"부산",a:"금정구 부산 부산광역시 "},
{s:"busan-gangseo",n:"부산 강서구",g:"부산",a:"강서구 부산 부산광역시 "},
{s:"busan-yeonje",n:"부산 연제구",g:"부산",a:"연제구 부산 부산광역시 "},
{s:"busan-suyeong",n:"부산 수영구",g:"부산",a:"수영구 부산 부산광역시 "},
{s:"busan-sasang",n:"부산 사상구",g:"부산",a:"사상구 부산 부산광역시 "},
{s:"busan-gijang",n:"부산 기장군",g:"부산",a:"기장군 부산 부산광역시 "},
{s:"daegu-junggu",n:"대구 중구",g:"대구",a:"중구 대구 대구광역시 "},
{s:"daegu-donggu",n:"대구 동구",g:"대구",a:"동구 대구 대구광역시 "},
{s:"daegu-seogu",n:"대구 서구",g:"대구",a:"서구 대구 대구광역시 "},
{s:"daegu-namgu",n:"대구 남구",g:"대구",a:"남구 대구 대구광역시 "},
{s:"daegu-bukgu",n:"대구 북구",g:"대구",a:"북구 대구 대구광역시 "},
{s:"daegu-suseong",n:"대구 수성구",g:"대구",a:"수성구 대구 대구광역시 "},
{s:"daegu-dalseo",n:"대구 달서구",g:"대구",a:"달서구 대구 대구광역시 "},
{s:"daegu-dalseong",n:"대구 달성군",g:"대구",a:"달성군 대구 대구광역시 "},
{s:"daegu-gunwi",n:"대구 군위군",g:"대구",a:"군위군 대구 대구광역시 "},
{s:"incheon-junggu",n:"인천 중구",g:"인천",a:"중구 인천 인천광역시 "},
{s:"incheon-donggu",n:"인천 동구",g:"인천",a:"동구 인천 인천광역시 "},
{s:"incheon-michuhol",n:"인천 미추홀구",g:"인천",a:"미추홀구 인천 인천광역시 "},
{s:"incheon-yeonsu",n:"인천 연수구",g:"인천",a:"연수구 인천 인천광역시 "},
{s:"incheon-namdong",n:"인천 남동구",g:"인천",a:"남동구 인천 인천광역시 "},
{s:"incheon-bupyeong",n:"인천 부평구",g:"인천",a:"부평구 인천 인천광역시 "},
{s:"incheon-gyeyang",n:"인천 계양구",g:"인천",a:"계양구 인천 인천광역시 "},
{s:"incheon-seogu",n:"인천 서구",g:"인천",a:"서구 인천 인천광역시 "},
{s:"incheon-ganghwa",n:"인천 강화군",g:"인천",a:"강화군 인천 인천광역시 "},
{s:"incheon-ongjin",n:"인천 옹진군",g:"인천",a:"옹진군 인천 인천광역시 "},
{s:"gwangju-donggu",n:"광주 동구",g:"광주",a:"동구 광주 광주광역시 "},
{s:"gwangju-seogu",n:"광주 서구",g:"광주",a:"서구 광주 광주광역시 "},
{s:"gwangju-namgu",n:"광주 남구",g:"광주",a:"남구 광주 광주광역시 "},
{s:"gwangju-bukgu",n:"광주 북구",g:"광주",a:"북구 광주 광주광역시 "},
{s:"gwangju-gwangsan",n:"광주 광산구",g:"광주",a:"광산구 광주 광주광역시 "},
{s:"daejeon-donggu",n:"대전 동구",g:"대전",a:"동구 대전 대전광역시 "},
{s:"daejeon-junggu",n:"대전 중구",g:"대전",a:"중구 대전 대전광역시 "},
{s:"daejeon-seogu",n:"대전 서구",g:"대전",a:"서구 대전 대전광역시 "},
{s:"daejeon-yuseong",n:"대전 유성구",g:"대전",a:"유성구 대전 대전광역시 "},
{s:"daejeon-daedeok",n:"대전 대덕구",g:"대전",a:"대덕구 대전 대전광역시 "},
{s:"ulsan-junggu",n:"울산 중구",g:"울산",a:"중구 울산 울산광역시 "},
{s:"ulsan-namgu",n:"울산 남구",g:"울산",a:"남구 울산 울산광역시 "},
{s:"ulsan-donggu",n:"울산 동구",g:"울산",a:"동구 울산 울산광역시 "},
{s:"ulsan-bukgu",n:"울산 북구",g:"울산",a:"북구 울산 울산광역시 "},
{s:"ulsan-ulju",n:"울산 울주군",g:"울산",a:"울주군 울산 울산광역시 "},
{s:"sejong",n:"세종",g:"세종",a:"세종 세종 세종특별자치시 세종시 "},
{s:"gyeonggi-suwon",n:"경기 수원시",g:"경기",a:"수원시 경기 경기도 "},
{s:"gyeonggi-seongnam",n:"경기 성남시",g:"경기",a:"성남시 경기 경기도 "},
{s:"gyeonggi-uijeongbu",n:"경기 의정부시",g:"경기",a:"의정부시 경기 경기도 "},
{s:"gyeonggi-anyang",n:"경기 안양시",g:"경기",a:"안양시 경기 경기도 "},
{s:"gyeonggi-bucheon",n:"경기 부천시",g:"경기",a:"부천시 경기 경기도 "},
{s:"gyeonggi-gwangmyeong",n:"경기 광명시",g:"경기",a:"광명시 경기 경기도 "},
{s:"gyeonggi-pyeongtaek",n:"경기 평택시",g:"경기",a:"평택시 경기 경기도 "},
{s:"gyeonggi-dongducheon",n:"경기 동두천시",g:"경기",a:"동두천시 경기 경기도 "},
{s:"gyeonggi-ansan",n:"경기 안산시",g:"경기",a:"안산시 경기 경기도 "},
{s:"gyeonggi-goyang",n:"경기 고양시",g:"경기",a:"고양시 경기 경기도 "},
{s:"gyeonggi-gwacheon",n:"경기 과천시",g:"경기",a:"과천시 경기 경기도 "},
{s:"gyeonggi-guri",n:"경기 구리시",g:"경기",a:"구리시 경기 경기도 "},
{s:"gyeonggi-namyangju",n:"경기 남양주시",g:"경기",a:"남양주시 경기 경기도 "},
{s:"gyeonggi-osan",n:"경기 오산시",g:"경기",a:"오산시 경기 경기도 "},
{s:"gyeonggi-siheung",n:"경기 시흥시",g:"경기",a:"시흥시 경기 경기도 "},
{s:"gyeonggi-gunpo",n:"경기 군포시",g:"경기",a:"군포시 경기 경기도 "},
{s:"gyeonggi-uiwang",n:"경기 의왕시",g:"경기",a:"의왕시 경기 경기도 "},
{s:"gyeonggi-hanam",n:"경기 하남시",g:"경기",a:"하남시 경기 경기도 "},
{s:"gyeonggi-yongin",n:"경기 용인시",g:"경기",a:"용인시 경기 경기도 "},
{s:"gyeonggi-paju",n:"경기 파주시",g:"경기",a:"파주시 경기 경기도 "},
{s:"gyeonggi-icheon",n:"경기 이천시",g:"경기",a:"이천시 경기 경기도 "},
{s:"gyeonggi-anseong",n:"경기 안성시",g:"경기",a:"안성시 경기 경기도 "},
{s:"gyeonggi-gimpo",n:"경기 김포시",g:"경기",a:"김포시 경기 경기도 "},
{s:"gyeonggi-hwaseong",n:"경기 화성시",g:"경기",a:"화성시 경기 경기도 "},
{s:"gyeonggi-gwangju",n:"경기 광주시",g:"경기",a:"광주시 경기 경기도 "},
{s:"gyeonggi-yangju",n:"경기 양주시",g:"경기",a:"양주시 경기 경기도 "},
{s:"gyeonggi-pocheon",n:"경기 포천시",g:"경기",a:"포천시 경기 경기도 "},
{s:"gyeonggi-yeoju",n:"경기 여주시",g:"경기",a:"여주시 경기 경기도 "},
{s:"gyeonggi-yeoncheon",n:"경기 연천군",g:"경기",a:"연천군 경기 경기도 "},
{s:"gyeonggi-gapyeong",n:"경기 가평군",g:"경기",a:"가평군 경기 경기도 "},
{s:"gyeonggi-yangpyeong",n:"경기 양평군",g:"경기",a:"양평군 경기 경기도 "},
{s:"gangwon-chuncheon",n:"강원 춘천시",g:"강원",a:"춘천시 강원 강원도 강원특별자치도 "},
{s:"gangwon-wonju",n:"강원 원주시",g:"강원",a:"원주시 강원 강원도 강원특별자치도 "},
{s:"gangwon-gangneung",n:"강원 강릉시",g:"강원",a:"강릉시 강원 강원도 강원특별자치도 "},
{s:"gangwon-donghae",n:"강원 동해시",g:"강원",a:"동해시 강원 강원도 강원특별자치도 "},
{s:"gangwon-taebaek",n:"강원 태백시",g:"강원",a:"태백시 강원 강원도 강원특별자치도 "},
{s:"gangwon-sokcho",n:"강원 속초시",g:"강원",a:"속초시 강원 강원도 강원특별자치도 "},
{s:"gangwon-samcheok",n:"강원 삼척시",g:"강원",a:"삼척시 강원 강원도 강원특별자치도 "},
{s:"gangwon-hongcheon",n:"강원 홍천군",g:"강원",a:"홍천군 강원 강원도 강원특별자치도 "},
{s:"gangwon-hoengseong",n:"강원 횡성군",g:"강원",a:"횡성군 강원 강원도 강원특별자치도 "},
{s:"gangwon-yeongwol",n:"강원 영월군",g:"강원",a:"영월군 강원 강원도 강원특별자치도 "},
{s:"gangwon-pyeongchang",n:"강원 평창군",g:"강원",a:"평창군 강원 강원도 강원특별자치도 "},
{s:"gangwon-jeongseon",n:"강원 정선군",g:"강원",a:"정선군 강원 강원도 강원특별자치도 "},
{s:"gangwon-cheorwon",n:"강원 철원군",g:"강원",a:"철원군 강원 강원도 강원특별자치도 "},
{s:"gangwon-hwacheon",n:"강원 화천군",g:"강원",a:"화천군 강원 강원도 강원특별자치도 "},
{s:"gangwon-yanggu",n:"강원 양구군",g:"강원",a:"양구군 강원 강원도 강원특별자치도 "},
{s:"gangwon-inje",n:"강원 인제군",g:"강원",a:"인제군 강원 강원도 강원특별자치도 "},
{s:"gangwon-goseong",n:"강원 고성군",g:"강원",a:"고성군 강원 강원도 강원특별자치도 "},
{s:"gangwon-yangyang",n:"강원 양양군",g:"강원",a:"양양군 강원 강원도 강원특별자치도 "},
{s:"chungbuk-cheongju",n:"충북 청주시",g:"충북",a:"청주시 충북 충청북도 "},
{s:"chungbuk-chungju",n:"충북 충주시",g:"충북",a:"충주시 충북 충청북도 "},
{s:"chungbuk-jecheon",n:"충북 제천시",g:"충북",a:"제천시 충북 충청북도 "},
{s:"chungbuk-boeun",n:"충북 보은군",g:"충북",a:"보은군 충북 충청북도 "},
{s:"chungbuk-okcheon",n:"충북 옥천군",g:"충북",a:"옥천군 충북 충청북도 "},
{s:"chungbuk-yeongdong",n:"충북 영동군",g:"충북",a:"영동군 충북 충청북도 "},
{s:"chungbuk-jeungpyeong",n:"충북 증평군",g:"충북",a:"증평군 충북 충청북도 "},
{s:"chungbuk-jincheon",n:"충북 진천군",g:"충북",a:"진천군 충북 충청북도 "},
{s:"chungbuk-goesan",n:"충북 괴산군",g:"충북",a:"괴산군 충북 충청북도 "},
{s:"chungbuk-eumseong",n:"충북 음성군",g:"충북",a:"음성군 충북 충청북도 "},
{s:"chungbuk-danyang",n:"충북 단양군",g:"충북",a:"단양군 충북 충청북도 "},
{s:"chungnam-cheonan",n:"충남 천안시",g:"충남",a:"천안시 충남 충청남도 "},
{s:"chungnam-gongju",n:"충남 공주시",g:"충남",a:"공주시 충남 충청남도 "},
{s:"chungnam-boryeong",n:"충남 보령시",g:"충남",a:"보령시 충남 충청남도 "},
{s:"chungnam-asan",n:"충남 아산시",g:"충남",a:"아산시 충남 충청남도 "},
{s:"chungnam-seosan",n:"충남 서산시",g:"충남",a:"서산시 충남 충청남도 "},
{s:"chungnam-nonsan",n:"충남 논산시",g:"충남",a:"논산시 충남 충청남도 "},
{s:"chungnam-gyeryong",n:"충남 계룡시",g:"충남",a:"계룡시 충남 충청남도 "},
{s:"chungnam-dangjin",n:"충남 당진시",g:"충남",a:"당진시 충남 충청남도 "},
{s:"chungnam-geumsan",n:"충남 금산군",g:"충남",a:"금산군 충남 충청남도 "},
{s:"chungnam-buyeo",n:"충남 부여군",g:"충남",a:"부여군 충남 충청남도 "},
{s:"chungnam-seocheon",n:"충남 서천군",g:"충남",a:"서천군 충남 충청남도 "},
{s:"chungnam-cheongyang",n:"충남 청양군",g:"충남",a:"청양군 충남 충청남도 "},
{s:"chungnam-hongseong",n:"충남 홍성군",g:"충남",a:"홍성군 충남 충청남도 "},
{s:"chungnam-yesan",n:"충남 예산군",g:"충남",a:"예산군 충남 충청남도 "},
{s:"chungnam-taean",n:"충남 태안군",g:"충남",a:"태안군 충남 충청남도 "},
{s:"jeonbuk-jeonju",n:"전북 전주시",g:"전북",a:"전주시 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-gunsan",n:"전북 군산시",g:"전북",a:"군산시 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-iksan",n:"전북 익산시",g:"전북",a:"익산시 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-jeongeup",n:"전북 정읍시",g:"전북",a:"정읍시 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-namwon",n:"전북 남원시",g:"전북",a:"남원시 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-gimje",n:"전북 김제시",g:"전북",a:"김제시 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-wanju",n:"전북 완주군",g:"전북",a:"완주군 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-jinan",n:"전북 진안군",g:"전북",a:"진안군 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-muju",n:"전북 무주군",g:"전북",a:"무주군 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-jangsu",n:"전북 장수군",g:"전북",a:"장수군 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-imsil",n:"전북 임실군",g:"전북",a:"임실군 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-sunchang",n:"전북 순창군",g:"전북",a:"순창군 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-gochang",n:"전북 고창군",g:"전북",a:"고창군 전북 전라북도 전북특별자치도 "},
{s:"jeonbuk-buan",n:"전북 부안군",g:"전북",a:"부안군 전북 전라북도 전북특별자치도 "},
{s:"jeonnam-mokpo",n:"전남 목포시",g:"전남",a:"목포시 전남 전라남도 "},
{s:"jeonnam-yeosu",n:"전남 여수시",g:"전남",a:"여수시 전남 전라남도 "},
{s:"jeonnam-suncheon",n:"전남 순천시",g:"전남",a:"순천시 전남 전라남도 "},
{s:"jeonnam-naju",n:"전남 나주시",g:"전남",a:"나주시 전남 전라남도 "},
{s:"jeonnam-gwangyang",n:"전남 광양시",g:"전남",a:"광양시 전남 전라남도 "},
{s:"jeonnam-damyang",n:"전남 담양군",g:"전남",a:"담양군 전남 전라남도 "},
{s:"jeonnam-gokseong",n:"전남 곡성군",g:"전남",a:"곡성군 전남 전라남도 "},
{s:"jeonnam-gurye",n:"전남 구례군",g:"전남",a:"구례군 전남 전라남도 "},
{s:"jeonnam-goheung",n:"전남 고흥군",g:"전남",a:"고흥군 전남 전라남도 "},
{s:"jeonnam-boseong",n:"전남 보성군",g:"전남",a:"보성군 전남 전라남도 "},
{s:"jeonnam-hwasun",n:"전남 화순군",g:"전남",a:"화순군 전남 전라남도 "},
{s:"jeonnam-jangheung",n:"전남 장흥군",g:"전남",a:"장흥군 전남 전라남도 "},
{s:"jeonnam-gangjin",n:"전남 강진군",g:"전남",a:"강진군 전남 전라남도 "},
{s:"jeonnam-haenam",n:"전남 해남군",g:"전남",a:"해남군 전남 전라남도 "},
{s:"jeonnam-yeongam",n:"전남 영암군",g:"전남",a:"영암군 전남 전라남도 "},
{s:"jeonnam-muan",n:"전남 무안군",g:"전남",a:"무안군 전남 전라남도 "},
{s:"jeonnam-hampyeong",n:"전남 함평군",g:"전남",a:"함평군 전남 전라남도 "},
{s:"jeonnam-yeonggwang",n:"전남 영광군",g:"전남",a:"영광군 전남 전라남도 "},
{s:"jeonnam-jangseong",n:"전남 장성군",g:"전남",a:"장성군 전남 전라남도 "},
{s:"jeonnam-wando",n:"전남 완도군",g:"전남",a:"완도군 전남 전라남도 "},
{s:"jeonnam-jindo",n:"전남 진도군",g:"전남",a:"진도군 전남 전라남도 "},
{s:"jeonnam-sinan",n:"전남 신안군",g:"전남",a:"신안군 전남 전라남도 "},
{s:"gyeongbuk-pohang",n:"경북 포항시",g:"경북",a:"포항시 경북 경상북도 "},
{s:"gyeongbuk-gyeongju",n:"경북 경주시",g:"경북",a:"경주시 경북 경상북도 "},
{s:"gyeongbuk-gimcheon",n:"경북 김천시",g:"경북",a:"김천시 경북 경상북도 "},
{s:"gyeongbuk-andong",n:"경북 안동시",g:"경북",a:"안동시 경북 경상북도 "},
{s:"gyeongbuk-gumi",n:"경북 구미시",g:"경북",a:"구미시 경북 경상북도 "},
{s:"gyeongbuk-yeongju",n:"경북 영주시",g:"경북",a:"영주시 경북 경상북도 "},
{s:"gyeongbuk-yeongcheon",n:"경북 영천시",g:"경북",a:"영천시 경북 경상북도 "},
{s:"gyeongbuk-sangju",n:"경북 상주시",g:"경북",a:"상주시 경북 경상북도 "},
{s:"gyeongbuk-mungyeong",n:"경북 문경시",g:"경북",a:"문경시 경북 경상북도 "},
{s:"gyeongbuk-gyeongsan",n:"경북 경산시",g:"경북",a:"경산시 경북 경상북도 "},
{s:"gyeongbuk-uiseong",n:"경북 의성군",g:"경북",a:"의성군 경북 경상북도 "},
{s:"gyeongbuk-cheongsong",n:"경북 청송군",g:"경북",a:"청송군 경북 경상북도 "},
{s:"gyeongbuk-yeongyang",n:"경북 영양군",g:"경북",a:"영양군 경북 경상북도 "},
{s:"gyeongbuk-yeongdeok",n:"경북 영덕군",g:"경북",a:"영덕군 경북 경상북도 "},
{s:"gyeongbuk-cheongdo",n:"경북 청도군",g:"경북",a:"청도군 경북 경상북도 "},
{s:"gyeongbuk-goryeong",n:"경북 고령군",g:"경북",a:"고령군 경북 경상북도 "},
{s:"gyeongbuk-seongju",n:"경북 성주군",g:"경북",a:"성주군 경북 경상북도 "},
{s:"gyeongbuk-chilgok",n:"경북 칠곡군",g:"경북",a:"칠곡군 경북 경상북도 "},
{s:"gyeongbuk-yecheon",n:"경북 예천군",g:"경북",a:"예천군 경북 경상북도 "},
{s:"gyeongbuk-bonghwa",n:"경북 봉화군",g:"경북",a:"봉화군 경북 경상북도 "},
{s:"gyeongbuk-uljin",n:"경북 울진군",g:"경북",a:"울진군 경북 경상북도 "},
{s:"gyeongbuk-ulleung",n:"경북 울릉군",g:"경북",a:"울릉군 경북 경상북도 "},
{s:"gyeongnam-changwon",n:"경남 창원시",g:"경남",a:"창원시 경남 경상남도 "},
{s:"gyeongnam-jinju",n:"경남 진주시",g:"경남",a:"진주시 경남 경상남도 "},
{s:"gyeongnam-tongyeong",n:"경남 통영시",g:"경남",a:"통영시 경남 경상남도 "},
{s:"gyeongnam-sacheon",n:"경남 사천시",g:"경남",a:"사천시 경남 경상남도 "},
{s:"gyeongnam-gimhae",n:"경남 김해시",g:"경남",a:"김해시 경남 경상남도 "},
{s:"gyeongnam-miryang",n:"경남 밀양시",g:"경남",a:"밀양시 경남 경상남도 "},
{s:"gyeongnam-geoje",n:"경남 거제시",g:"경남",a:"거제시 경남 경상남도 "},
{s:"gyeongnam-yangsan",n:"경남 양산시",g:"경남",a:"양산시 경남 경상남도 "},
{s:"gyeongnam-uiryeong",n:"경남 의령군",g:"경남",a:"의령군 경남 경상남도 "},
{s:"gyeongnam-haman",n:"경남 함안군",g:"경남",a:"함안군 경남 경상남도 "},
{s:"gyeongnam-changnyeong",n:"경남 창녕군",g:"경남",a:"창녕군 경남 경상남도 "},
{s:"gyeongnam-goseong",n:"경남 고성군",g:"경남",a:"고성군 경남 경상남도 "},
{s:"gyeongnam-namhae",n:"경남 남해군",g:"경남",a:"남해군 경남 경상남도 "},
{s:"gyeongnam-hadong",n:"경남 하동군",g:"경남",a:"하동군 경남 경상남도 "},
{s:"gyeongnam-sancheong",n:"경남 산청군",g:"경남",a:"산청군 경남 경상남도 "},
{s:"gyeongnam-hamyang",n:"경남 함양군",g:"경남",a:"함양군 경남 경상남도 "},
{s:"gyeongnam-geochang",n:"경남 거창군",g:"경남",a:"거창군 경남 경상남도 "},
{s:"gyeongnam-hapcheon",n:"경남 합천군",g:"경남",a:"합천군 경남 경상남도 "},
{s:"jeju-jeju",n:"제주 제주시",g:"제주",a:"제주시 제주 제주도 제주특별자치도 "},
{s:"jeju-seogwipo",n:"제주 서귀포시",g:"제주",a:"서귀포시 제주 제주도 제주특별자치도 "},
];
